"""Switch telegram_id to BIGINT

Revision ID: 6082b26db63d
Revises: 67e07e7ac522
Create Date: 2023-02-26 11:31:24.148980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6082b26db63d'
down_revision = '67e07e7ac522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
